####################
  # APP PLAYBOOK #
#####################
- name: Deploy Django App
  hosts: all   
  become: true
  vars:
    app_dir: /opt/flight_prices
  roles:
  - docker  
  

  tasks:

    # Копирование репозитория в папку на вм
    - name: Create directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy files
      ansible.builtin.copy:
        src: /root/aviasales/flight_prices/
        dest: "{{ app_dir }}"
        remote_src: no

    # docker-compose up -d
    - name: Run docker-compose
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: "{{ app_dir }}"
